### ISSUE TITLE
Game hangs when trying to load world.

### ISSUE THREAD

**Issue by ausera** [xtreme8000/CavEX#11]
happened on dolphin and real console.
it would be stuck on the loading world screen.

**Comment by xtreme8000** [comment]
Does it show "Building terrain" with the progress bar not moving? And what kind of world are you trying to load? It needs to be compatible with Beta 1.7.3

**Comment by ausera** [comment]
@xtreme8000 yes the progress bar is not moving and yes its compatible with beta 1.7.3

**Comment by xtreme8000** [comment]
Then which version of cavex? I need more info

**Comment by ausera** [comment]
compiled it myself. newest version. @xtreme8000
