### ISSUE TITLE
Leaf block rendering inconsistency

### ISSUE THREAD

**Issue by SmollestBug** [xtreme8000/CavEX#13]
Unlike the original Java versions. Leaves don't backface cull in CavEX. If you place a leaf surrounded by air then you'll see all sides through the block, rather than only the sides that face you. When placed against a block then they cull normally, with the exception of when placed next to spruce leaves, where depending on the facing direction it chooses whether to render the spruce leaves face, or the oak leaves face.

I'm not sure if this difference actually does have any bearing on performance, but just noting this for the fact that I could assume the extra leaf faces could be cut and help with the higher rendering time in forested areas exhibited ingame.

**Comment by xtreme8000** [comment]
This is on purpose for performance reasons.
