### ISSUE TITLE
CavEX DOL File

### ISSUE THREAD

**Issue by Alexis20000** [xtreme8000/CavEX#14]
I can not compile the CODE, I tried many times to compile it but each time it never works can you distribute a link in the description of the project (CavEX) which sends us a google drive or a OneDrive which contains a pack that contains the executable file (DOL File) by the homebrew channel. But please give a file the dol file of the new version please 🥺🥺

**Comment by SmollestBug** [comment]
What step are you caught up on? I could give some more indepth instructions based on where you got stuck. It'd be easier when you know how to consistently compile rather than waiting for an already compiled release version.

**Comment by Alexis20000** [comment]
it's time when I have to add the folders and files but above all what blocks me the most is the makefile can you make me a video so that I understand everything please 🥺🥺🥺🥺🥺.

**Comment by Alexis20000** [comment]
you managed to get the dol file and the rest so can you give it to me via a google drive or a OneDrive or by putting the dol file in the window of your new comment but if it doesn't work try to give me the dol file by a google drive link which contains the dol file that you have, therefore the dol file that you have, the assets folder which contains the file terrain.png, items.png, anim.png, default.png, gui.png, and the file gui2.png and you will add in this same folder a folder named gui and in this famous folder gui, there will be a file named inventory.png which is in the source code of the project.
but if we go back to where the dol file is, you will put the config.json file, the icon.png and the meta.xml file, I don't need them. and if it doesn't work you will try to do it with the OneDrive.
please do it for me please.
