### ISSUE TITLE
Add Classic Controller Support

### ISSUE THREAD

**Issue by CatastrophicDino** [xtreme8000/CavEX#3]
Are there any plans to add classic controller support? they're perfect for playing minecraft with the only execptions being crouching and third person but they could be implemented in a different way or just not be implemented at all.

**Comment by xtreme8000** [comment]
closed by 8304df7ecb03c5a2bd38b75da11bbcc50e654f46

**Comment by groggone** [comment]
At first sight i thought this was for the Ace of Spades client "BetterSpades", turns out it is still dead

**Comment by xtreme8000** [comment]
@groggone BS already has controller support 💀
