### ISSUE TITLE
Resource pack manager.

### ISSUE THREAD

**Issue by toadragethe5th** [xtreme8000/CavEX#30]
Hi! 

Me and my friend are massive fans of your work, and Wii homebrew in general. I was wondering if I can publish a Resource Pack manager for your project. I have it all coded and everything, and it works by overriding your PNG files in the assets directory. Do I have permission to release this?

**Comment by madboy234** [comment]
That would be really cool if Byte added your epic feature!

**Comment by xtreme8000** [comment]
Sure, you don't need my permission on this.
However, it is planned to add texturepack management into the game itself and rn you can already choose a different pack by changing the entry in `config.json`.

**Comment by toadragethe5th** [comment]
Oh okay, thank you for your permission

**Comment by madboy234** [comment]
> Oh okay, thank you for your permission

Where will you release it?

**Comment by toadragethe5th** [comment]
> > Oh okay, thank you for your permission
> 
> Where will you release it?

I already have

Check my profile

**Comment by madboy234** [comment]
> > > Oh okay, thank you for your permission
> > 
> > 
> > Where will you release it?
> 
> I already have
> 
> Check my profile

Yeah, I figured it out, although it's kind of a bit to difficult to install 😅😅

**Comment by toadragethe5th** [comment]
> > > > Oh okay, thank you for your permission
> > > 
> > > 
> > > Where will you release it?
> > 
> > I already have
> > 
> > Check my profile
> 
> Yeah, I figured it out, although it's kind of a bit to difficult to install 😅😅

What is the problem?

**Comment by toadragethe5th** [comment]
I added lots of documentation

**Comment by madboy234** [comment]
> I added lots of documentation

Yeah, I will try to read them

**Comment by toadragethe5th** [comment]
So it's not a problem with installation, it's just that you were confused on how to install it
