### ISSUE TITLE
gfx_setup: Assertion `vertex' failed.

### ISSUE THREAD

**Issue by Squidtito** [xtreme8000/CavEX#4]
I have compiled CavEX for Linux, I am on Arch Linux. I had to use a alternative to "glfw3", I installed glfw-X11 (I also used glfw-wayland).

I keep on getting this:
cavex: /mnt/441c3dff-f2cf-45ea-bfc6-063ea6aa249f/Doc/CavEX/source/platform/pc/gfx.c:196: gfx_setup: Assertion `vertex' failed.
Aborted (core dumped)

this is the structure of the directory
![image](https://github.com/xtreme8000/CavEX/assets/62845931/b8102112-80b3-474c-8d8b-1b92c8c820af)

**Comment by xtreme8000** [comment]
Right, contrary to what the README says, it now expects the `fragment.shader` and `vertex.shader` files in the assets directory.

**Comment by Squidtito** [comment]
It works, I feel like this section was a bit misleading?
![image](https://github.com/xtreme8000/CavEX/assets/62845931/ff14e862-8a52-4521-b13f-b454e555fa5a)

**Comment by tbaiense** [comment]
Might be obvious to many, but it was not for me (first time compiling a C project written by someone else): make sure to move the built `cavex` to root directory, as the files are loaded relatively. I was trying to execute from the `build_pc` directory and it failed trying to load `assets/vertex.shader` and `assets/fragment.shader`.
