### ISSUE TITLE
[PC] Game doesn't start.

### ISSUE THREAD

**Issue by CDM15y** [xtreme8000/CavEX#47]
The game doesn't run, here is the log:

```
Vendor: Intel
Renderer: Mesa Mobile Intel® GM45 Express Chipset (CTG)
Version: 2.1 Mesa 24.1.0-arch1.1
cavex: /home/cdm/git-repos/CavEX/source/platform/pc/gfx.c:140: gfx_setup: Assertion `vertex' failed.
[1]    5801 IOT instruction (core dumped)  ./cavex
```

OS: Arch Linux x86-64
Kernel: Linux 6.9.3-arch1-1

**Comment by xtreme8000** [comment]
see #4 #39 #43

**Comment by CDM15y** [comment]
The game now works but it's unresponsive.

**Comment by NihilisticPuffin** [comment]
You need to copy the config_pc.json file into the same directory as the executable and rename it to config.json for it to work
