### ISSUE TITLE
Function for Multiplayer support and arrival

### ISSUE THREAD

**Issue by Caveproject** [xtreme8000/CavEX#60]
Hi xtreme8000, Can you please or any possibility of adding multiplayer support? Either by the same console or a server perhaps?

**Comment by Caveproject** [comment]
Is it a possibility for the near future? I can't wait to have it implemented on the Wii! Please let me know your thoughts

**Comment by xtreme8000** [comment]
Yes, the code base is already designed with future server-based multiplayer in mind.

**Comment by Caveproject** [comment]
Great! Hope to see it soon!

**Comment by Caveproject** [comment]
Hi Xtreme8000, When can we expect the multiplayer feature to be implemented? I am excited for its arrival.

**Comment by Caveproject** [comment]
Hi Xtreme8000, I just wanted to know if you have received my comment. Thanks in advance

**Comment by xtreme8000** [comment]
Yes, I read every comment. Sorry I did not reply. The project is currently on hold and will be for the foreseeable future.
