### ISSUE TITLE
PC version does not start

### ISSUE THREAD

**Issue by Kamion008** [xtreme8000/CavEX#64]
when I start the pc version of cavEX it does not start and instead throws this error:
`./cavex                            
Vendor: AMD
Renderer: AMD Radeon Graphics (radeonsi, raphael_mendocino, LLVM 18.1.8, DRM 3.59, 6.12.7-arch1-1)
Version: 4.6 (Compatibility Profile) Mesa 24.3.2-arch1.1
cavex: /home/kamion008/Downloads/cavEX/CavEX/source/platform/pc/gfx.c:140: gfx_setup: Assertion `vertex' failed.
[1]    65385 IOT instruction (core dumped)  ./cavex`

**Comment by xtreme8000** [comment]
see #47
