### ISSUE TITLE
Problem of the inventory

### ISSUE THREAD

**Issue by Alexis20000** [xtreme8000/CavEX#8]
the problem is that the inventory never wants to open I even looked in the game code, PS: I have no knowledge by the way, if we talk about the problem in the game code it says to press button 1 on the Wii remote to open the inventory, but when I press this button in the middle of a game the inventory does not open. But on the interface that goes up which button corresponds to which action it says to press the A button of the Wii Remote to open the inventory, but obviously it does not open, so can you add a functional inventory to which we can take / get items like in the creative mode of Minecraft Beta 1.8 / 1.8.1
please 🙂🙂🙂🙂🙂☺☺☺☺☺.

**Comment by minecraftlover6273** [comment]
Maybe he will add the inventory in the next update? If the inventory button is there saying it’s the 1 button on the Wiimote maybe he just has it there as a placeholder until he finishes it I would assume

**Comment by ausera** [comment]
The inventory code does not even exist yet lmao

**Comment by minecraftlover6273** [comment]
Yeah, that's what a placeholder does. Bytebit probably has made code for it but it's not currently in our copy of CavEX

**Comment by xtreme8000** [comment]
Inventory added since 37e335b98f2c4eaa55b7f4cc5bda9fb2ba3572ff
