### ISSUE TITLE
Probleme of build the game: collect2.exe: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by Alexis20000** [xtreme8000/CavEX#9]
the error code is: collect2.exe: error: ld returned 1 exit status
make[1]: *** [/opt/devkitpro/devkitPPC/wii_rules:31: /home/*****/Downloads/Homebrew_tutorial/Tutorial/Tutorial.elf] Error 1
make: *** [Makefile:112: build] Error 2

**Comment by Alexis20000** [comment]
can you just give a dol file / the executable file of the game by the wii in the code tab please

**Comment by xtreme8000** [comment]
it says `Homebrew_tutorial/Tutorial/Tutorial.elf`, how is this even related to CavEX

**Comment by Alexis20000** [comment]
Is a tutoriel pack to create elf/dol files
